package com.example.myquizapplication;

public class QuestionAnswer {

    public static String question[] = {
            "What is the chemical symbol for gold?",
            "Which river is the longest in the world?",
            "Who was the first President of the United States?",
            "In which film did Leonardo DiCaprio win his first Academy Award for Best Actor?",
            "Which country won the FIFA World Cup in 2018?",
            "Who wrote the play \"Romeo and Juliet\"?",
            "Which company developed the first commercially available personal computer?",
            "What instrument does Yo-Yo Ma play?",
            "What is the value of pi (π) to two decimal places?",
            "What is the capital city of Australia?",
            "Who painted the Mona Lisa?",
            "What is the capital of Japan?",
            "Which gas do plants primarily absorb from the atmosphere?",
            "What is the currency of Brazil?",
            "Who wrote the famous play \"Hamlet\"?",
            "What is the largest organ in the human body?",
            "Which country is known as the \"Land of the Rising Sun\"?",
            "What is the main ingredient in guacamole?",
            "Who developed the theory of relativity?",
            "What is the capital of Canada?",
            "What is the largest desert in the world?",
            "Who wrote \"Pride and Prejudice\"?",
            "In which year did the Titanic sink?",
            "What is the chemical symbol for water?",
            "Who is known as the \"Father of Computer Science\"?",
            "Which planet is known as the \"Blue Planet\"?",
            "What is the currency of South Africa?",
            "Who wrote \"The Great Gatsby\"?",
            "What is the world's largest ocean mammal?",
            "What is the capital of South Korea?",
            "Who is the author of \"The Catcher in the Rye\"?",
            "Which element has the chemical symbol 'K'?",
            "What is the world's largest rainforest?",
            "Who painted \"Starry Night\"?",
            "What is the capital of New Zealand?",
            "Which famous scientist formulated the laws of motion and universal gravitation?",
            "In which year did the Berlin Wall fall?",
            "What is the main gas responsible for the greenhouse effect?",
            "Who wrote \"The Odyssey\"?",
            "What is the smallest prime number?",
            "What is the capital of South Africa?",
            "Who is the protagonist in J.K. Rowling's Harry Potter series?",
            "What is the largest planet in our solar system?",
            "Who wrote the play \"Macbeth\"?",
            "Which continent is known as the \"Dark Continent\"?",
            "What is the chemical symbol for iron?",
            "In which year did the United States gain independence from Great Britain?",
            "Which famous scientist developed the theory of general relativity?",
            "What is the capital of Argentina?",
            "Which is the longest river in the world?"
    };

    public static String choices[][] = {
            {"Go","Au","Ag","Ge"},
            {"Amazon","Nile","Yangtze","Mississippi"},
            {"Thomas Jefferson","George Washington","Abraham Lincoln","John Adams"},
            {"The Revenant","Titanic","Inception","The Wolf of Wall Street"},
            {"Brazil","Germany","France","Argentina"},
            {"Charles Dickens","William Shakespeare","Jane Austen","Emily Brontë"},
            {"IBM","Apple","Microsoft","Intel"},
            {"Violin","Cello","Piano","Flute"},
            {"3.14","3.16","3.18","3.20"},
            {"Sydney","Melbourne","Canberra","Brisbane"},
            {"Vincent van Gogh","Leonardo da Vinci","Pablo Picasso","Michelangelo"},
            {"Beijing","Tokyo","Seoul","Bangkok"},
            {"Oxygen","Carbon Monoxide","Carbon Dioxide","Nitrogen"},
            {"Peso","Euro","Real","Baht"},
            {"Charles Dickens","William Shakespeare","Jane Austen","Fyodor Dostoevsky"},
            {"Liver","Heart","Skin","Lungs"},
            {"China","Japan","South Korea","Vietnam"},
            {"Tomatoes","Avocado","Onions","Peppers"},
            {"Isaac Newton","Albert Einstein","Galileo Galilei","Stephen Hawking"},
            {"Toronto","Ottawa","Vancouver","Montreal"},
            {"Sahara Desert","Gobi Desert","Antarctic Desert","Arabian Desert"},
            {"Jane Austen","Emily Brontë","Charlotte Brontë","Charles Dickens"},
            {"1910","1912","1915","1917"},
            {"Wo","H2O","O2","CO2"},
            {"Alan Turing","Bill Gates","Steve Jobs","Mark Zuckerberg"},
            {"Earth","Mars","Venus","Neptune"},
            {"Rand","Peso","Baht","Euro"},
            {"F. Scott Fitzgerald","Ernest Hemingway","Mark Twain","J.K. Rowling"},
            {"Dolphin","Blue Whale","Shark","Seal"},
            {"Seoul","Tokyo","Beijing","Hanoi"},
            {"J.D. Salinger","F. Scott Fitzgerald","Ernest Hemingway","Mark Twain"},
            {"Potassium","Krypton","Nickel","Cobalt"},
            {"Amazon Rainforest","Congo Rainforest","Borneo Rainforest","Daintree Rainforest"},
            {"Pablo Picasso","Vincent van Gogh","Leonardo da Vinci","Claude Monet"},
            {"Wellington","Sydney","Auckland","Canberra"},
            {"Isaac Newton","Albert Einstein","Galileo Galilei","Johannes Kepler"},
            {"1985","1989","1991","1995"},
            {"Carbon Dioxide","Methane","Nitrous Oxide","Ozone"},
            {"Homer","Virgil","Sophocles","Aesop"},
            {"0","1","2","3"},
            {"Johannesburg","Cape Town","Pretoria","Durban"},
            {"Hermione Granger","Ron Weasley","Harry Potter","Draco Malfoy"},
            {"Mars","Jupiter","Saturn","Venus"},
            {"William Shakespeare","Jane Austen","Charles Dickens","F. Scott Fitzgerald"},
            {"Asia","Africa","South America","Antarctica"},
            {"Ir","Fe","In","Au"},
            {"1765","1776","1789","1801"},
            {"Isaac Newton","Albert Einstein","Stephen Hawking","Galileo Galilei"},
            {"Rio de Janeiro","Buenos Aires","Santiago","Lima"},
            {"Amazon River","Nile River","Yangtze River","Mississippi River"}
    };

    public static String correctAnswer[] = {
            "Au",
            "Nile",
            "George Washington",
            "The Revenant",
            "France",
            "William Shakespeare",
            "IBM",
            "Cello",
            "3.14",
            "Canberra",
            "Leonardo da Vinci",
            "Tokyo",
            "Carbon Dioxide",
            "Real",
            "William Shakespeare",
            "Skin",
            "Japan",
            "Avocado",
            "Albert Einstein",
            "Ottawa",
            "Antarctic Desert",
            "Jane Austen",
            "1912",
            "H2O",
            "Alan Turing",
            "Earth",
            "Rand",
            "F. Scott Fitzgerald",
            "Blue Whale",
            "Seoul",
            "J.D. Salinger",
            "Potassium",
            "Amazon Rainforest",
            "Vincent van Gogh",
            "Wellington",
            "Isaac Newton",
            "1989",
            "Carbon Dioxide",
            "Homer",
            "2",
            "Pretoria",
            "Harry Potter",
            "Jupiter",
            "William Shakespeare",
            "Africa",
            "Fe",
            "1776",
            "Albert Einstein",
            "Buenos Aires",
            "Nile River"
    };
}
